//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaDeviceBuilder.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaDeviceBuilder.WPF.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-update (мс).
        /// </summary>
        public static string AutoUpdateMs {
            get {
                return ResourceManager.GetString("AutoUpdateMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a new VISA device instance of type &quot;{0}&quot;..
        /// </summary>
        public static string CannotCreateVisaDeviceInstance {
            get {
                return ResourceManager.GetString("CannotCreateVisaDeviceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect device.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-initializing.
        /// </summary>
        public static string DeInitializing {
            get {
                return ResourceManager.GetString("DeInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device identifier.
        /// </summary>
        public static string DeviceIdentifier {
            get {
                return ResourceManager.GetString("DeviceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect device.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified VISA resource manager type &quot;{0}&quot; does not implement the &quot;{1}&quot; interface..
        /// </summary>
        public static string InvalidResourceManagerType {
            get {
                return ResourceManager.GetString("InvalidResourceManagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified VISA device type &quot;{0}&quot; does not implement the &quot;{1}&quot; interface..
        /// </summary>
        public static string InvalidVisaDeviceType {
            get {
                return ResourceManager.GetString("InvalidVisaDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message response.
        /// </summary>
        public static string MessageResponse {
            get {
                return ResourceManager.GetString("MessageResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other actions.
        /// </summary>
        public static string OtherActions {
            get {
                return ResourceManager.GetString("OtherActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value.
        /// </summary>
        public static string PropertyActualValue {
            get {
                return ResourceManager.GetString("PropertyActualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name.
        /// </summary>
        public static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value.
        /// </summary>
        public static string PropertyNewValue {
            get {
                return ResourceManager.GetString("PropertyNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update properties.
        /// </summary>
        public static string UpdateProperties {
            get {
                return ResourceManager.GetString("UpdateProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISA resource name.
        /// </summary>
        public static string VisaResourceName {
            get {
                return ResourceManager.GetString("VisaResourceName", resourceCulture);
            }
        }
    }
}
