//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaDeviceBuilder.WPF.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaDeviceBuilder.WPF.App.Resources.Localization.ru", typeof(Localization_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение с плавающей точкой.
        /// </summary>
        public static string FloatingPointAsyncProperty {
            get {
                return ResourceManager.GetString("FloatingPointAsyncProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение только для чтения.
        /// </summary>
        public static string GetOnlyAsyncProperty {
            get {
                return ResourceManager.GetString("GetOnlyAsyncProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целочисленное значение.
        /// </summary>
        public static string IntegerAsyncProperty {
            get {
                return ResourceManager.GetString("IntegerAsyncProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайное значение.
        /// </summary>
        public static string RandomAsyncProperty {
            get {
                return ResourceManager.GetString("RandomAsyncProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение только для записи.
        /// </summary>
        public static string SetOnlyAsyncProperty {
            get {
                return ResourceManager.GetString("SetOnlyAsyncProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строковое значение.
        /// </summary>
        public static string StringAsyncProperty {
            get {
                return ResourceManager.GetString("StringAsyncProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовое действие.
        /// </summary>
        public static string TestDeviceAction {
            get {
                return ResourceManager.GetString("TestDeviceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовое текстовое устройство.
        /// </summary>
        public static string TestMessageDevice {
            get {
                return ResourceManager.GetString("TestMessageDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контрольная панель для устройств VISA.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
