//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaDeviceBuilder.SampleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaDeviceBuilder.SampleApp.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emit a beep.
        /// </summary>
        public static string Beep {
            get {
                return ResourceManager.GetString("Beep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output current limit (A).
        /// </summary>
        public static string CurrentLimit {
            get {
                return ResourceManager.GetString("CurrentLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device display text.
        /// </summary>
        public static string DisplayedText {
            get {
                return ResourceManager.GetString("DisplayedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device display is enabled.
        /// </summary>
        public static string IsDisplayEnabled {
            get {
                return ResourceManager.GetString("IsDisplayEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device output is enabled.
        /// </summary>
        public static string IsOutputEnabled {
            get {
                return ResourceManager.GetString("IsOutputEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over-voltage protection is enabled.
        /// </summary>
        public static string IsOverVoltageProtectionEnabled {
            get {
                return ResourceManager.GetString("IsOverVoltageProtectionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured output current (A).
        /// </summary>
        public static string MeasuredCurrent {
            get {
                return ResourceManager.GetString("MeasuredCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured output voltage (V).
        /// </summary>
        public static string MeasuredVoltage {
            get {
                return ResourceManager.GetString("MeasuredVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over-voltage protection level (V).
        /// </summary>
        public static string OverVoltageLevel {
            get {
                return ResourceManager.GetString("OverVoltageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the device front panel.
        /// </summary>
        public static string SetControlLock {
            get {
                return ResourceManager.GetString("SetControlLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the device front panel control.
        /// </summary>
        public static string SetLocalControl {
            get {
                return ResourceManager.GetString("SetLocalControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the device remote control.
        /// </summary>
        public static string SetRemoteControl {
            get {
                return ResourceManager.GetString("SetRemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target output voltage (V).
        /// </summary>
        public static string TargetVoltage {
            get {
                return ResourceManager.GetString("TargetVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISA device control panel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
